[tool.poetry]
name = "py-tests"
version = "0.1.0"
description = ""
authors = ["Autor...."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^8.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
